apiVersion: builds.okderators.io/v1alpha1
kind: Recipe
metadata:
  labels:
    app.kubernetes.io/name: recipe
    app.kubernetes.io/instance: recipe-sample
    app.kubernetes.io/part-of: operator-builder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-builder
  name: recipe-sample
spec:
  operator:
    version: test
    repoUrl: test
    repoRef: test
